# Generated by Django 3.2 on 2023-06-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'PENDIENTE'), ('terminado', 'TERMINADO')], default='pendiente', max_length=20),
        ),
    ]
